#include <iostream>
#include <string>
#include <vector>
using namespace std;

int main() {
	vector<vector<string> > v; 
	vector<string> Apc={CCTTCTACACAGTACACCCG,TGAGCCGGGAGACATGATAT,ATCACTACACCCCTATTGAG,GTTTCCCCATATAGGTCAAG,CTAGAGTCCAGCTACACGTG};
	vector<string> Trp53={GAAGTCACAGCACATGACGG,AACAGATCGTCCATGCAGTG,GTGTAATAGCTCCTGCATGG,GGTACCTTATGAGCCACCCG,TCCACCCGGATAAGATGCTG}
	vector<string> Pten={CCTCCAATTCAGGACCCACG,TGTGCATATTTATTGCATCG,ACTATTCCAATGTTCAGTGG,GGTTTGATAAGTTCTAGCTG,GAGTCACAATTCCCAGTCAG}
	vector<string> Smad4={TGAATCCATATCACTATGAG,CAAAAGCGATCTCCTCCCGA,GGTGGCGTTAGACTCTGCCG,TGTCACCATACAGAGAACAT,AGTCCTACTTCCAGTCCAGG}
	vector<string> Arid1a={GCAGCTGCGAAGATATCGGG,CAGCAGAACTCGCACGACCA,CCTGCTGGCCATACGCACTG,TACCCAAATATGAATCAAGG,AGGCATGAGATTTGGCTGAG}
	vector<string> Tgfbr2={CCTACGAGGAGTACTCCTCG,ACCTGCAGGAGTACCTCACG,GAAGCCGCATGAAGTCTGCG,CATGACATCACTGTTAACTG,ACAGCTATGGCAATCCCCAG}
	vector<string> Cdkn2a={GCAGCTCTTCTGCTCAACTA,GCGCTGCGTCGTGCACCGGG,GGGCCGCCCACTCCAAGAGA,CTTTCGTGAACATGTTGTTG,TGGTGAAGTTCGTGCGATCC}
	vector<string> Rb1={AAATGATACGAGGATTATCG,TAAGTACGTTCAGAATCCAC,GAGAAGTTTGCTAACGCTGT,GCAGTATGGTTACCCTGGAG,TTACTCCACACACTCCAGTT}
	/*for (int i = 0; i < 5; i++) {
		for (int j = 0; j < 5; j++) {
			cout << 
		}
	}*/
	return 0;
}